export const houses = [
  {
    "id": 1,
    "type": "Hus",
    "address": "Topvägen 41",
    "price": 1000000,
    "rooms": 4,
    "area": 130,
    "Balcony": "Balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 3,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 2022,
    "Storehouse": "Förråd",
    "ParkingLot": "Garage",
    "Courtyard": "Tomt"
  },
  {
    "id": 2,
    "type": "Lägenhet",
    "address": "Kunskapsvägen 50",
    "price": 750000,
    "rooms": 2,
    "area": 75,
    "Balcony": "Balkong",
    "Outdoors": "Uteplats",
    "Floor": 6,
    "Elevator": "Hiss",
    "YearOfBuilding": 1999,
    "Storehouse": "Förråd",
    "ParkingLot": "Parkering",
    "Courtyard": "Ingen innergård"
  },
  {
    "id": 3,
    "type": "Villa",
    "address": "Villaville kulla 2",
    "price": 1500000,
    "rooms": 5,
    "area": 180,
    "Balcony": "Balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 2,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 1980,
    "Storehouse": "Förråd",
    "ParkingLot": "Parkering",
    "Courtyard": "Tomt"
  },
  {
    "id": 4,
    "type": "Hus",
    "address": "Mariegatan 75",
    "price": 900000,
    "rooms": 3,
    "area": 90,
    "Balcony": "Ingen balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 1,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 1890,
    "Storehouse": "Jordkälla",
    "ParkingLot": "Parkering",
    "Courtyard": "Tomt"
  },
  {
    "id": 5,
    "type": "Lägenhet",
    "address": "Torevägen 58",
    "price": 1000000,
    "rooms": 4,
    "area": 110,
    "Balcony": "Balkong",
    "Outdoors": "Uteplats",
    "Floor": 3,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 1960,
    "Storehouse": "Förråd",
    "ParkingLot": "Ingen parkering",
    "Courtyard": "Ingen innergård"
  },
  {
    "id": 6,
    "type": "Villa",
    "address": "Kalasvägen 23",
    "price": 1100000,
    "rooms": 4,
    "area": 140,
    "Balcony": "Balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 3,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 1970,
    "Storehouse": "Förråd",
    "ParkingLot": "Parkering",
    "Courtyard": "Tomt"
  },
  {
    "id": 7,
    "type": "Hus",
    "address": "Elvägen 1",
    "price": 1700000,
    "rooms": 6,
    "area": 190,
    "Balcony": "Balkong",
    "Outdoors": "Uteplats",
    "Floor": 2,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 2000,
    "Storehouse": "Förråd",
    "ParkingLot": "Garage",
    "Courtyard": "Tomt"
  },
  {
    "id": 8,
    "type": "Lägenhet",
    "address": "Technogatan 30",
    "price": 1000000,
    "rooms": 3,
    "area": 90,
    "Balcony": "Balkong",
    "Outdoors": "Uteplats",
    "Floor": 7,
    "Elevator": "Hiss",
    "Year of building": 2023,
    "Storehouse": "Förråd",
    "Parking lot": "Garage",
    "Courtyard": "Ingen innergård"
  },
  {
    "id": 9,
    "type": "Villa",
    "address": "Lockelookvägen 53",
    "price": 1400000,
    "rooms": 4,
    "area": 110,
    "Balcony": "Ingen balkong",
    "Outdoors": "Uteplats",
    "Floor": 1,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 1860,
    "Storehouse": "Jordkälla",
    "Parking lot": "Parkering",
    "Courtyard": "Tomt"
  },
  {
    "id": 10,
    "type": "Hus",
    "address": "Triptraptrullgatan 10",
    "price": 800000,
    "rooms": 3,
    "area": 80,
    "Balcony": "Ingen balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 1,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 1968,
    "Storehouse": "Förråd",
    "ParkingLot": "Ingen parkering",
    "Courtyard": "Tomt"
  },
  {
    "id": 11,
    "type": "Lägenhet",
    "address": "Skyrocketvägen 48",
    "price": 950000,
    "rooms": 3,
    "area": 79,
    "Balcony": "Ingen balkong",
    "Outdoors": "Uteplats",
    "Floor": 4,
    "Elevator": "Hiss",
    "YearOfBuilding": 2015,
    "Storehouse": "Förråd",
    "ParkingLot": "Parkering",
    "Courtyard": "Ingen innergård"
  },
  {
    "id": 12,
    "type": "Villa",
    "address": "Booleangatan 55",
    "price": 1200000,
    "rooms": 4,
    "area": 100,
    "Balcony": "Balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 2,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 2017,
    "Storehouse": "Förråd",
    "ParkingLot": "Garage",
    "Courtyard": "Tomt"
  },
  {
    "id": 13,
    "type": "Hus",
    "address": "Bergodalbanevägen 40",
    "price": 1500000,
    "rooms": 4,
    "area": 130,
    "Balcony": "Balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 3,
    "Elevator": "Hiss",
    "YearOfBuilding": 2020,
    "Storehouse": "Förråd",
    "ParkingLot": "Garage",
    "Courtyard": "Tomt"
  },
  {
    "id": 14,
    "type": "Lägenhet",
    "address": "Muffingatan 21",
    "price": 650000,
    "rooms": 2,
    "area": 55,
    "Balcony": "Ingen balkong",
    "Outdoors": "Uteplats",
    "Floor": 2,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 1888,
    "Storehouse": "Jordkälla",
    "ParkingLot": "Ingen parkering",
    "Courtyard": "Ingen innergård"
  },
  {
    "id": 15,
    "type": "Villa",
    "address": "Dragondalsgatan",
    "price": 1200000,
    "rooms": 3,
    "area": 100,
    "Balcony": "Balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 1,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 2003,
    "Storehouse": "Förråd",
    "ParkingLot": "Parkering",
    "Courtyard": "Tomt"
  },
  {
    "id": 16,
    "type": "Hus",
    "address": "Krokodilvägen 39",
    "price": 900000,
    "rooms": 3,
    "area": 90,
    "Balcony": "Ingen balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 1,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 2005,
    "Storehouse": "Förråd",
    "ParkingLot": "Parkering",
    "Courtyard": "Tomt"
  },
  {
    "id": 17,
    "type": "Lägenhet",
    "address": "Spacevägen",
    "price": 900000,
    "rooms": 3,
    "area": 87,
    "Balcony": "Ingen balkong",
    "Outdoors": "Uteplats",
    "Floor": 1,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 1970,
    "Storehouse": "Inget förråd",
    "Parking lot": "Ingen parkering",
    "Courtyard": "Ingen innergård"
  },
  {
    "id": 18,
    "type": "Villa",
    "address": "Programmeringsgatan 37",
    "price": 1500000,
    "rooms": 5,
    "area": 135,
    "Balcony": "Balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 4,
    "Elevator": "Hiss",
    "YearOfBuilding": 2023,
    "Storehouse": "Förråd",
    "ParkingLot": "Garage",
    "Courtyard": "Tomt"
  },
  {
    "id": 19,
    "type": "Hus",
    "address": "Fridofröjdvägen 50",
    "price": 1300000,
    "rooms": 4,
    "area": 115,
    "Balcony": "Ingen balkong",
    "Outdoors": "Ingen uteplats",
    "Floor": 2,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 1970,
    "Storehouse": "Inget förråd",
    "ParkingLot": "Ingen parkering",
    "Courtyard": "Tomt"
  },
  {
    "id": 20,
    "type": "Lägenhet",
    "address": "Grafikvägen 25",
    "price": 1000000,
    "rooms": 3,
    "area": 82,
    "Balcony": "Ingen balkong",
    "Outdoors": "Uteplats",
    "Floor": 5,
    "Elevator": "Ingen hiss",
    "YearOfBuilding": 1985,
    "Storehouse": "Förråd",
    "ParkingLot": "Ingen parkering",
    "Courtyard": "Ingen innergård"
  }
]